repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: no-commit-to-branch
        args: [--branch, main]

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$
    -   id: cmake-lint
        types: [file]
        files: (\.cmake|CMakeLists.txt)(.in)?$

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: remove-tabs

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.4
    hooks:
    -   id: clang-format
        args: [-i]
    -   id: clang-tidy
    -   id: cpplint
    -   id: cppcheck
        args: [--template=gcc, --std=c++11,
               --enable=style,performance,warning,portability, --inline-suppr,
               --suppress=internalAstError, --suppress=unmatchedSuppression,
               --inconclusive, -ithird_party]

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--settings-path=pyproject.toml]
