name: ci-windows

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build-type: [Release, Debug]
        python:
          - 3.7
          - 3.8
          - 3.9

    name: "Build: ${{matrix.os}} • ${{matrix.python}} • ${{matrix.build-type}}"
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python ${{matrix.python}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}

    - name: Prepare Python Environment
      run: python -m pip install -r requirements.txt

    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.14.1
      with:
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build C++ Project
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

    - name: Run C++ Tests
      run: ctest --test-dir ${{github.workspace}}/build/tests/cpp
